#[cfg(unix)]
use std::fs::File;
#[cfg(unix)]
use std::io::Read;
#[cfg(unix)]
use std::os::unix::fs::MetadataExt;
use std::path::{Path, PathBuf};

use anvil_storage::v1::object_chunk::Value as ObjectChunkValue;
use anvil_storage::v1::object_head::State as ObjectHeadState;
use anvil_storage::v1::object_version::State as ObjectVersionState;
use anvil_storage::v1::put_header::Operation as PutOperation;
use anvil_storage::v1::{
    BucketPolicy, CreateBucketRequest, DeleteIfVersionRequest, DeleteRequest, DeleteVersionRequest,
    Durability, GetObjectRequest, HeadObjectRequest, InvokeProgramRequest,
    ListObjectVersionsRequest, ListObjectsRequest, ObjectAddress, ObjectVersioning,
    ProvisionTenantRequest, PutHeader, PutIfAbsentOperation, PutIfVersionOperation,
    PutImmutableOperation, PutOperation as UnconditionalPutOperation, PutRequest,
    SetBucketPolicyRequest, SetBucketVersioningRequest,
};
use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand, ValueEnum};
use serde::Deserialize;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio_stream::wrappers::ReceiverStream;

const CHUNK_BYTES: usize = 256 * 1024;
const MAX_CREDENTIAL_FILE_BYTES: u64 = 4 * 1024;

#[derive(Parser)]
#[command(name = "anvil", version, about = "Anvil 0.5 client")]
struct Arguments {
    #[arg(long, env = "ANVIL_ENDPOINT", default_value = "http://127.0.0.1:50051")]
    endpoint: String,

    /// A short-lived access token. Prefer client credentials for unattended use.
    #[arg(long, env = "ANVIL_ACCESS_TOKEN", hide_env_values = true)]
    token: Option<String>,

    /// JSON credential file generated by system bootstrap.
    #[arg(long, env = "ANVIL_CREDENTIALS_FILE")]
    credentials_file: Option<PathBuf>,

    #[arg(long, env = "ANVIL_CLIENT_ID")]
    client_id: Option<String>,

    #[arg(long, env = "ANVIL_CLIENT_SECRET", hide_env_values = true)]
    client_secret: Option<String>,

    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    Put {
        tenant: String,
        bucket: String,
        path: String,
        file: PathBuf,
        #[arg(long)]
        content_type: Option<String>,
        #[arg(long)]
        command_id: String,
        #[arg(long, value_enum, default_value = "local")]
        durability: DurabilityArgument,
        #[arg(long)]
        if_absent: bool,
        #[arg(long)]
        if_version: Option<u64>,
        #[arg(long)]
        immutable: bool,
    },
    Get {
        tenant: String,
        bucket: String,
        path: String,
        #[arg(long)]
        version: Option<u64>,
        #[arg(long)]
        output: Option<PathBuf>,
    },
    Head {
        tenant: String,
        bucket: String,
        path: String,
    },
    /// Return one lexical page of current live paths.
    List {
        tenant: String,
        bucket: String,
        #[arg(long, default_value = "")]
        prefix: String,
        #[arg(long)]
        start_after: Option<String>,
        #[arg(long, default_value_t = 100)]
        limit: u32,
    },
    Delete {
        tenant: String,
        bucket: String,
        path: String,
        #[arg(long)]
        command_id: String,
        #[arg(long, value_enum, default_value = "local")]
        durability: DurabilityArgument,
        #[arg(long)]
        if_version: Option<u64>,
    },
    /// Permanently remove one retained version (current live becomes a tombstone).
    DeleteVersion {
        tenant: String,
        bucket: String,
        path: String,
        version: u64,
        #[arg(long, value_enum, default_value = "local")]
        durability: DurabilityArgument,
    },
    /// Stream retained metadata for one exact path from oldest to newest.
    ListVersions {
        tenant: String,
        bucket: String,
        path: String,
    },
    SetPolicy {
        tenant: String,
        bucket: String,
        #[arg(long = "immutable")]
        immutable: Vec<String>,
        #[arg(long = "program-only")]
        program_only: Vec<String>,
    },
    InvokeProgram {
        tenant: String,
        bucket: String,
        program_path: String,
        invocation_id: String,
        #[arg(long)]
        program_hash: String,
        #[arg(long, value_enum, default_value = "local")]
        durability: DurabilityArgument,
        input: PathBuf,
    },
    /// Create a tenant and its first owner credential as the system administrator.
    ProvisionTenant {
        storage_tenant: String,
        owner_app_id: String,
        owner_client_id: String,
        #[arg(long, env = "ANVIL_NEW_CLIENT_SECRET", hide_env_values = true)]
        owner_client_secret: String,
    },
    /// Create one bucket and make the authenticated application its owner.
    CreateBucket {
        bucket: String,
        #[arg(long, value_enum, default_value = "unversioned")]
        versioning: VersioningArgument,
    },
    /// Permanently enable retained object versions for one existing bucket.
    EnableBucketVersioning { bucket: String },
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum DurabilityArgument {
    Local,
    Replicated,
}

impl From<DurabilityArgument> for i32 {
    fn from(value: DurabilityArgument) -> Self {
        match value {
            DurabilityArgument::Local => Durability::Local as i32,
            DurabilityArgument::Replicated => Durability::Replicated as i32,
        }
    }
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum VersioningArgument {
    Unversioned,
    Enabled,
}

impl From<VersioningArgument> for i32 {
    fn from(value: VersioningArgument) -> Self {
        match value {
            VersioningArgument::Unversioned => ObjectVersioning::Unversioned as i32,
            VersioningArgument::Enabled => ObjectVersioning::Enabled as i32,
        }
    }
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct CredentialFile {
    schema: String,
    storage_tenant: String,
    app_id: String,
    client_id: String,
    client_secret: String,
}

#[tokio::main]
async fn main() -> Result<()> {
    let arguments = Arguments::parse();
    let channel = anvil_storage::connect_channel(&arguments.endpoint)
        .await
        .map_err(|error| anyhow::anyhow!(error.to_string()))?;
    let access_token = resolve_access_token(&arguments, channel.clone()).await?;
    let mut client = anvil_storage::object_client(channel.clone(), &access_token)?;
    let mut administration = anvil_storage::administration_client(channel, &access_token)?;
    match arguments.command {
        Command::Put {
            tenant,
            bucket,
            path,
            file,
            content_type,
            command_id,
            durability,
            if_absent,
            if_version,
            immutable,
        } => {
            let operation = put_operation(if_absent, if_version, immutable)?;
            let receipt = put_file(
                &mut client,
                PutHeader {
                    address: Some(address(tenant, bucket, path)),
                    content_type: content_type.unwrap_or_default(),
                    command_id,
                    durability: durability.into(),
                    operation: Some(operation),
                },
                file,
            )
            .await?;
            println!("{}", receipt.version);
        }
        Command::Get {
            tenant,
            bucket,
            path,
            version,
            output,
        } => {
            let mut stream = client
                .get_object(GetObjectRequest {
                    address: Some(address(tenant, bucket, path)),
                    version,
                })
                .await?
                .into_inner();

            let first = stream
                .message()
                .await?
                .ok_or_else(|| anyhow::anyhow!("server returned an empty object stream"))?;
            let present = match first.value {
                Some(ObjectChunkValue::Head(head)) => match head.state {
                    Some(ObjectHeadState::Present(present)) => present,
                    Some(ObjectHeadState::Deleted(deleted)) => {
                        bail!("object is deleted at version {}", deleted.version)
                    }
                    Some(ObjectHeadState::NeverExisted(_)) => bail!("object never existed"),
                    None => bail!("server returned an empty object state"),
                },
                Some(ObjectChunkValue::Bytes(_)) => {
                    bail!("server sent object bytes before the object state")
                }
                None => bail!("server returned an empty object chunk"),
            };
            if present.content_hash.len() != 32 {
                bail!("present object has an invalid content hash");
            }
            let expected_hash = present.content_hash;
            let expected_bytes = present.content_length;
            let mut file = match output {
                Some(path) => Some(tokio::fs::File::create(path).await?),
                None => None,
            };
            let mut stdout = tokio::io::stdout();
            let mut observed_bytes = 0_u64;
            let mut observed_hash = blake3::Hasher::new();
            while let Some(chunk) = stream.message().await? {
                match chunk.value {
                    Some(ObjectChunkValue::Bytes(bytes)) => {
                        observed_bytes = observed_bytes
                            .checked_add(bytes.len() as u64)
                            .ok_or_else(|| anyhow::anyhow!("object length overflow"))?;
                        if observed_bytes > expected_bytes {
                            bail!("server streamed more bytes than the object head declared");
                        }
                        observed_hash.update(&bytes);
                        match file.as_mut() {
                            Some(file) => file.write_all(&bytes).await?,
                            None => stdout.write_all(&bytes).await?,
                        }
                    }
                    Some(ObjectChunkValue::Head(_)) => {
                        bail!("server sent more than one object state")
                    }
                    None => bail!("server returned an empty object chunk"),
                }
            }
            if observed_bytes != expected_bytes {
                bail!(
                    "server streamed {observed_bytes} bytes but the object head declared {expected_bytes}"
                );
            }
            if observed_hash.finalize().as_bytes() != expected_hash.as_slice() {
                bail!("server streamed bytes that do not match the object head hash");
            }
        }
        Command::Head {
            tenant,
            bucket,
            path,
        } => {
            let head = client
                .head_object(HeadObjectRequest {
                    address: Some(address(tenant, bucket, path)),
                })
                .await?
                .into_inner();
            match head.state {
                Some(ObjectHeadState::Present(present)) => println!(
                    "present version={} bytes={}",
                    present.version, present.content_length
                ),
                Some(ObjectHeadState::Deleted(deleted)) => {
                    println!("deleted version={}", deleted.version)
                }
                Some(ObjectHeadState::NeverExisted(_)) => println!("never-existed"),
                None => bail!("server returned an empty object state"),
            }
        }
        Command::List {
            tenant,
            bucket,
            prefix,
            start_after,
            limit,
        } => {
            let response = client
                .list_objects(ListObjectsRequest {
                    tenant,
                    bucket,
                    prefix,
                    start_after,
                    limit,
                })
                .await?
                .into_inner();
            for path in &response.paths {
                println!("{path}");
            }
            if response.has_more {
                let cursor = response.paths.last().ok_or_else(|| {
                    anyhow::anyhow!("server returned has_more without a continuation path")
                })?;
                eprintln!("more paths available; resume with --start-after {cursor:?}");
            }
        }
        Command::Delete {
            tenant,
            bucket,
            path,
            command_id,
            durability,
            if_version,
        } => {
            let object_address = Some(address(tenant, bucket, path));
            let receipt = match if_version {
                Some(expected_version) => client
                    .delete_if_version(DeleteIfVersionRequest {
                        address: object_address,
                        command_id,
                        durability: durability.into(),
                        expected_version,
                    })
                    .await?
                    .into_inner(),
                None => client
                    .delete(DeleteRequest {
                        address: object_address,
                        command_id,
                        durability: durability.into(),
                    })
                    .await?
                    .into_inner(),
            };
            println!("{}", receipt.version);
        }
        Command::DeleteVersion {
            tenant,
            bucket,
            path,
            version,
            durability,
        } => {
            let response = client
                .delete_version(DeleteVersionRequest {
                    address: Some(address(tenant, bucket, path)),
                    version,
                    durability: durability.into(),
                })
                .await?
                .into_inner();
            match response.replacement_tombstone_version {
                Some(version) => {
                    println!(
                        "deleted={} replacement_tombstone_version={version}",
                        response.deleted
                    )
                }
                None => println!(
                    "deleted={} replacement_tombstone_version=none",
                    response.deleted
                ),
            }
        }
        Command::ListVersions {
            tenant,
            bucket,
            path,
        } => {
            let mut versions = client
                .list_object_versions(ListObjectVersionsRequest {
                    address: Some(address(tenant, bucket, path)),
                })
                .await?
                .into_inner();
            while let Some(version) = versions.message().await? {
                match version.state {
                    Some(ObjectVersionState::Present(present)) => println!(
                        "present version={} bytes={} content_type={}",
                        present.version, present.content_length, present.content_type
                    ),
                    Some(ObjectVersionState::Deleted(deleted)) => {
                        println!("deleted version={}", deleted.version)
                    }
                    None => bail!("server returned an empty retained-version state"),
                }
            }
        }
        Command::SetPolicy {
            tenant,
            bucket,
            mut immutable,
            mut program_only,
        } => {
            immutable.sort();
            immutable.dedup();
            program_only.sort();
            program_only.dedup();
            client
                .set_bucket_policy(SetBucketPolicyRequest {
                    tenant,
                    bucket,
                    policy: Some(BucketPolicy {
                        immutable_path_prefixes: immutable,
                        program_only_path_prefixes: program_only,
                    }),
                })
                .await?;
        }
        Command::InvokeProgram {
            tenant,
            bucket,
            program_path,
            invocation_id,
            program_hash,
            durability,
            input,
        } => {
            let input_json = tokio::fs::read(input).await?;
            let response = client
                .invoke_program(InvokeProgramRequest {
                    program: Some(address(tenant, bucket, program_path)),
                    invocation_id,
                    program_hash: parse_hex(&program_hash)?,
                    input_json,
                    durability: durability.into(),
                })
                .await?
                .into_inner();
            tokio::io::stdout().write_all(&response.output_json).await?;
            tokio::io::stdout().write_all(b"\n").await?;
        }
        Command::ProvisionTenant {
            storage_tenant,
            owner_app_id,
            owner_client_id,
            owner_client_secret,
        } => {
            let response = administration
                .provision_tenant(ProvisionTenantRequest {
                    storage_tenant,
                    owner_app_id,
                    owner_client_id,
                    owner_client_secret,
                })
                .await?
                .into_inner();
            let credential = response
                .credential
                .ok_or_else(|| anyhow::anyhow!("server omitted the owner credential"))?;
            println!(
                "tenant={} app={} client={} revision={} replayed={}",
                credential.storage_tenant,
                credential.app_id,
                credential.client_id,
                response.authorization_revision,
                response.replayed,
            );
        }
        Command::CreateBucket { bucket, versioning } => {
            let response = administration
                .create_bucket(CreateBucketRequest {
                    bucket,
                    versioning: versioning.into(),
                })
                .await?
                .into_inner();
            let versioning = versioning_name(response.versioning)?;
            println!(
                "tenant={} bucket={} versioning={} revision={} replayed={}",
                response.storage_tenant,
                response.bucket,
                versioning,
                response.authorization_revision,
                response.replayed,
            );
        }
        Command::EnableBucketVersioning { bucket } => {
            let response = administration
                .set_bucket_versioning(SetBucketVersioningRequest {
                    bucket,
                    versioning: ObjectVersioning::Enabled as i32,
                })
                .await?
                .into_inner();
            println!(
                "tenant={} bucket={} versioning={} changed={}",
                response.storage_tenant,
                response.bucket,
                versioning_name(response.versioning)?,
                response.changed,
            );
        }
    }
    Ok(())
}

async fn resolve_access_token(
    arguments: &Arguments,
    channel: tonic::transport::Channel,
) -> Result<String> {
    let credential_sources = usize::from(arguments.token.is_some())
        + usize::from(arguments.credentials_file.is_some())
        + usize::from(arguments.client_id.is_some() || arguments.client_secret.is_some());
    if credential_sources != 1 {
        bail!(
            "supply exactly one of --token, --credentials-file, or the --client-id/--client-secret pair"
        );
    }
    if let Some(token) = arguments.token.as_ref() {
        if token.is_empty() {
            bail!("--token must not be empty");
        }
        return Ok(token.clone());
    }
    let (client_id, client_secret) = match arguments.credentials_file.as_ref() {
        Some(path) => {
            let bytes = load_credential_file(path)?;
            let credential = decode_bootstrap_credential(&bytes)?;
            (credential.client_id, credential.client_secret)
        }
        None => {
            let client_id = arguments.client_id.clone().ok_or_else(|| {
                anyhow::anyhow!("--client-id and --client-secret are required together")
            })?;
            let client_secret = arguments.client_secret.clone().ok_or_else(|| {
                anyhow::anyhow!("--client-id and --client-secret are required together")
            })?;
            (client_id, client_secret)
        }
    };
    let token = anvil_storage::exchange_client_credentials(channel, client_id, client_secret)
        .await
        .context("exchange client credentials")?;
    if token.token_type != "Bearer"
        || token.access_token.is_empty()
        || token.expires_in_seconds == 0
    {
        bail!("credential exchange returned an invalid access token");
    }
    Ok(token.access_token)
}

fn load_credential_file(path: &Path) -> Result<Vec<u8>> {
    #[cfg(not(unix))]
    {
        let _ = path;
        bail!("mode-0600 credential files require a Unix host");
    }
    #[cfg(unix)]
    {
        let before = std::fs::symlink_metadata(path)
            .with_context(|| format!("inspect credential file {}", path.display()))?;
        if !before.file_type().is_file() || before.file_type().is_symlink() {
            bail!("credential path must name a regular non-symlink file");
        }
        if before.mode() & 0o7777 != 0o600 {
            bail!("credential file mode must be exactly 0600");
        }

        let mut file =
            File::open(path).with_context(|| format!("open credential file {}", path.display()))?;
        let opened = file
            .metadata()
            .with_context(|| format!("inspect opened credential file {}", path.display()))?;
        if !opened.file_type().is_file()
            || opened.dev() != before.dev()
            || opened.ino() != before.ino()
            || opened.mode() & 0o7777 != 0o600
        {
            bail!("credential file changed while it was being opened");
        }

        let mut bytes = Vec::new();
        (&mut file)
            .take(MAX_CREDENTIAL_FILE_BYTES + 1)
            .read_to_end(&mut bytes)
            .with_context(|| format!("read credential file {}", path.display()))?;
        if bytes.len() as u64 > MAX_CREDENTIAL_FILE_BYTES {
            bail!("credential file exceeds {MAX_CREDENTIAL_FILE_BYTES} bytes");
        }
        let after = file
            .metadata()
            .with_context(|| format!("reinspect credential file {}", path.display()))?;
        if !after.file_type().is_file()
            || after.dev() != before.dev()
            || after.ino() != before.ino()
            || after.mode() & 0o7777 != 0o600
        {
            bail!("credential file changed while it was being read");
        }
        Ok(bytes)
    }
}

fn decode_bootstrap_credential(bytes: &[u8]) -> Result<CredentialFile> {
    let credential: CredentialFile =
        serde_json::from_slice(bytes).context("decode credential file JSON")?;
    if credential.schema != "anvil.system-bootstrap-credential.v1"
        || credential.storage_tenant != "_anvil"
        || credential.app_id.is_empty()
        || credential.client_id.is_empty()
        || credential.client_secret.is_empty()
    {
        bail!("credential file is not a valid Anvil system-bootstrap credential");
    }
    Ok(credential)
}

async fn put_file(
    client: &mut anvil_storage::RawClient,
    header: PutHeader,
    path: PathBuf,
) -> Result<anvil_storage::v1::MutationReceipt> {
    let mut file = tokio::fs::File::open(&path)
        .await
        .with_context(|| format!("open {}", path.display()))?;
    let metadata = file
        .metadata()
        .await
        .with_context(|| format!("inspect {}", path.display()))?;
    if !metadata.is_file() {
        bail!("put input must be a regular file");
    }
    let expected_bytes = metadata.len();
    let token = client.start_put(header).await?.into_inner();
    let (sender, receiver) = tokio::sync::mpsc::channel(4);
    let (completion_sender, completion_receiver) = tokio::sync::oneshot::channel();
    let producer = tokio::spawn(async move {
        let outcome = async {
            let mut observed_bytes = 0_u64;
            let mut sent_chunk = false;
            loop {
                let mut bytes = vec![0_u8; CHUNK_BYTES];
                let read = file
                    .read(&mut bytes)
                    .await
                    .map_err(|error| format!("read put input: {error}"))?;
                if read == 0 {
                    if observed_bytes != expected_bytes {
                        return Err(format!(
                            "put input changed while reading: expected {expected_bytes} bytes, observed {observed_bytes}"
                        ));
                    }
                    if !sent_chunk {
                        sender
                            .send(PutRequest {
                                token: Some(token.clone()),
                                chunk: Vec::new(),
                            })
                            .await
                            .map_err(|_| "put RPC stopped accepting chunks".to_owned())?;
                    }
                    break;
                }
                observed_bytes = observed_bytes
                    .checked_add(read as u64)
                    .ok_or_else(|| "put input length overflow".to_owned())?;
                if observed_bytes > expected_bytes {
                    return Err(format!(
                        "put input changed while reading: expected {expected_bytes} bytes, observed more"
                    ));
                }
                bytes.truncate(read);
                sent_chunk = true;
                sender
                    .send(PutRequest {
                        token: Some(token.clone()),
                        chunk: bytes,
                    })
                    .await
                    .map_err(|_| "put RPC stopped accepting chunks".to_owned())?;
            }
            Ok::<(), String>(())
        }
        .await;
        let failed = outcome.is_err();
        let _ = completion_sender.send(outcome);
        if failed {
            // Retain the request sender until the caller cancels the RPC. A
            // local read failure must never look like a clean end-of-stream,
            // which would unnecessarily seal a partial staged object.
            std::future::pending::<()>().await;
        }
    });
    let ready = {
        let request = client.put(ReceiverStream::new(receiver));
        tokio::pin!(request);
        tokio::pin!(completion_receiver);
        let response = tokio::select! {
            biased;
            completion = &mut completion_receiver => {
                match completion.context("put input task stopped without a result")? {
                    Ok(()) => request.await?,
                    Err(error) => {
                        producer.abort();
                        bail!(error);
                    }
                }
            }
            response = &mut request => {
                producer.abort();
                response?
            }
        };
        if !producer.is_finished() {
            producer.await.context("put input task panicked")?;
        }
        response.into_inner()
    };
    Ok(client.put_end(ready).await?.into_inner())
}

fn address(tenant: String, bucket: String, path: String) -> ObjectAddress {
    ObjectAddress {
        tenant,
        bucket,
        path,
    }
}

fn versioning_name(value: i32) -> Result<&'static str> {
    match ObjectVersioning::try_from(value) {
        Ok(ObjectVersioning::Unversioned) => Ok("unversioned"),
        Ok(ObjectVersioning::Enabled) => Ok("enabled"),
        Err(_) => bail!("server returned an unknown object versioning mode"),
    }
}

fn put_operation(
    if_absent: bool,
    if_version: Option<u64>,
    immutable: bool,
) -> Result<PutOperation> {
    match (if_absent, if_version, immutable) {
        (true, None, false) => Ok(PutOperation::PutIfAbsent(PutIfAbsentOperation {})),
        (false, Some(expected_version), false) => {
            Ok(PutOperation::PutIfVersion(PutIfVersionOperation {
                expected_version,
            }))
        }
        (false, None, true) => Ok(PutOperation::PutImmutable(PutImmutableOperation {})),
        (false, None, false) => Ok(PutOperation::Put(UnconditionalPutOperation {})),
        _ => bail!("--if-absent, --if-version, and --immutable are mutually exclusive"),
    }
}

fn parse_hex(value: &str) -> Result<Vec<u8>> {
    if value.len() != 64 || !value.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        bail!("program hash must be the 64-digit BLAKE3 hash of the stored definition bytes");
    }
    value
        .as_bytes()
        .chunks_exact(2)
        .map(|pair| {
            let pair = std::str::from_utf8(pair).expect("hexadecimal input is ASCII");
            u8::from_str_radix(pair, 16).context("invalid program hash")
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::{
        Arguments, Command, VersioningArgument, decode_bootstrap_credential, load_credential_file,
        parse_hex, put_operation, versioning_name,
    };
    use anvil_storage::v1::put_header::Operation;
    use clap::Parser as _;
    #[cfg(unix)]
    use std::os::unix::fs::{PermissionsExt, symlink};

    #[test]
    fn program_hash_is_exactly_one_blake3_digest() {
        assert_eq!(parse_hex(&"ab".repeat(32)).unwrap(), vec![0xab; 32]);
        for invalid in [
            String::new(),
            "ab".repeat(31),
            "ab".repeat(33),
            "gg".repeat(32),
        ] {
            assert!(parse_hex(&invalid).is_err());
        }
    }

    #[test]
    fn put_flags_select_exactly_one_typed_operation() {
        assert!(matches!(
            put_operation(false, None, false).unwrap(),
            Operation::Put(_)
        ));
        assert!(matches!(
            put_operation(true, None, false).unwrap(),
            Operation::PutIfAbsent(_)
        ));
        assert!(
            matches!(put_operation(false, Some(8), false).unwrap(), Operation::PutIfVersion(request) if request.expected_version == 8)
        );
        assert!(matches!(
            put_operation(false, None, true).unwrap(),
            Operation::PutImmutable(_)
        ));
        assert!(put_operation(true, Some(8), false).is_err());
        assert!(put_operation(true, None, true).is_err());
    }

    #[test]
    fn versioning_names_are_closed_and_zero_is_meaningful() {
        assert_eq!(versioning_name(0).unwrap(), "unversioned");
        assert_eq!(
            versioning_name(anvil_storage::v1::ObjectVersioning::Enabled as i32).unwrap(),
            "enabled"
        );
        assert!(versioning_name(99).is_err());
    }

    #[test]
    fn version_management_commands_are_explicit() {
        let default_create =
            Arguments::try_parse_from(["anvil", "--token", "token", "create-bucket", "objects"])
                .unwrap();
        assert!(matches!(
            default_create.command,
            Command::CreateBucket {
                versioning: VersioningArgument::Unversioned,
                ..
            }
        ));

        let create = Arguments::try_parse_from([
            "anvil",
            "--token",
            "token",
            "create-bucket",
            "objects",
            "--versioning",
            "enabled",
        ])
        .unwrap();
        assert!(matches!(
            create.command,
            Command::CreateBucket {
                versioning: VersioningArgument::Enabled,
                ..
            }
        ));

        let delete = Arguments::try_parse_from([
            "anvil",
            "--token",
            "token",
            "delete-version",
            "acme",
            "objects",
            "record.json",
            "17",
        ])
        .unwrap();
        assert!(matches!(
            delete.command,
            Command::DeleteVersion { version: 17, .. }
        ));

        let enable = Arguments::try_parse_from([
            "anvil",
            "--token",
            "token",
            "enable-bucket-versioning",
            "objects",
        ])
        .unwrap();
        assert!(matches!(
            enable.command,
            Command::EnableBucketVersioning { ref bucket } if bucket == "objects"
        ));
    }

    #[test]
    fn bootstrap_credential_file_is_strict_and_never_needs_to_be_logged() {
        let valid = br#"{
            "schema":"anvil.system-bootstrap-credential.v1",
            "storage_tenant":"_anvil",
            "app_id":"bootstrap-1",
            "client_id":"client-1",
            "client_secret":"secret-value"
        }"#;
        let decoded = decode_bootstrap_credential(valid).unwrap();
        assert_eq!(decoded.client_id, "client-1");
        assert_eq!(decoded.client_secret, "secret-value");

        for invalid in [
            br#"{}"#.as_slice(),
            br#"{"schema":"wrong","storage_tenant":"_anvil","app_id":"a","client_id":"c","client_secret":"s"}"#.as_slice(),
            br#"{"schema":"anvil.system-bootstrap-credential.v1","storage_tenant":"_anvil","app_id":"a","client_id":"c","client_secret":"s","extra":true}"#.as_slice(),
        ] {
            assert!(decode_bootstrap_credential(invalid).is_err());
        }
    }

    #[cfg(unix)]
    #[test]
    fn credential_file_loader_requires_stable_regular_mode_0600_bounded_file() {
        let directory = tempfile::tempdir().unwrap();
        let credential = directory.path().join("credential.json");
        std::fs::write(&credential, b"{}").unwrap();
        std::fs::set_permissions(&credential, std::fs::Permissions::from_mode(0o600)).unwrap();
        assert_eq!(load_credential_file(&credential).unwrap(), b"{}");

        std::fs::set_permissions(&credential, std::fs::Permissions::from_mode(0o644)).unwrap();
        assert!(load_credential_file(&credential).is_err());
        std::fs::set_permissions(&credential, std::fs::Permissions::from_mode(0o600)).unwrap();

        let link = directory.path().join("credential-link.json");
        symlink(&credential, &link).unwrap();
        assert!(load_credential_file(&link).is_err());

        let oversized = directory.path().join("oversized.json");
        std::fs::write(
            &oversized,
            vec![0_u8; super::MAX_CREDENTIAL_FILE_BYTES as usize + 1],
        )
        .unwrap();
        std::fs::set_permissions(&oversized, std::fs::Permissions::from_mode(0o600)).unwrap();
        assert!(load_credential_file(&oversized).is_err());
    }

    #[cfg(not(unix))]
    #[test]
    fn credential_file_loader_fails_closed_without_unix_file_modes() {
        assert!(load_credential_file(std::path::Path::new("credential.json")).is_err());
    }
}
