[package]
name = "anvil-storage"
version = "0.9.5"
edition.workspace = true
description = "Deprecated crate name; use keldra"
rust-version.workspace = true
license-file = "../../LICENSE"
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/keldra"
readme = "README.md"
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
keldra = { version = "=0.1.0", path = "../rust" }
