[package]
name = "anvil-api"
version = "0.9.4"
edition.workspace = true
license-file = "../../LICENSE"
rust-version.workspace = true
description = "Rust gRPC API types for Anvil object storage"
homepage.workspace = true
documentation = "https://docs.rs/anvil-api"
readme = "README.md"
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
prost = "0.14"
prost-types = "0.14"
tonic = { version = "0.14", features = ["transport"] }
tonic-prost = "0.14"

[build-dependencies]
tonic-prost-build = "0.14"
