[package]
name = "anvil-storage"
version.workspace = true
edition.workspace = true
description = "Authenticated Rust client for Anvil objects and indexes"
rust-version.workspace = true
license-file = "../../LICENSE"
homepage.workspace = true
documentation = "https://docs.rs/anvil-storage"
readme = "README.md"
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anvil-api = { version = "0.7.0", path = "../../crates/anvil-api" }
tokio-stream = "0.1"
tonic = { version = "0.14", default-features = false, features = ["transport", "tls-native-roots"] }

[dev-dependencies]
tokio = { version = "1.47", features = ["macros", "rt"] }
